CREATE TABLE roles (
  id BINARY(16) NOT NULL,
  role VARCHAR(45) NOT NULL,
  status ENUM('ACTIVE', 'INACTIVE') DEFAULT 'ACTIVE' NOT NULL,
  created_date DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
  inactive_date DATETIME DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE INDEX role_unq (role ASC) VISIBLE);